name: Create Resume PDF and Release

on:
  push:
    branches:
      - main
    paths:
      - cli/**
      - resume/**
      - .github/workflows/release.yml
      - Dockerfile

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  LATEX_PACKAGES: >-
    cjk
    pdfx
    embedfile
    arydshln
    standalone
    import
    moresize
    anyfontsize
    csquotes
    enumitem
    titlesec
    blindtext

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: ./cli

      - name: Sync LaTeX files
        run: bun run sync
        working-directory: ./cli

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: resume
          root_file: resume.tex
          scheme: small
          extra_packages: ${{ env.LATEX_PACKAGES }}

      - name: Create release
        run: gh release create v${{ github.run_number }} --title "Resume v${{ github.run_number }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset
        run: gh release upload v${{ github.run_number }} ./resume/resume.pdf --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
